In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
mpg = sns.load_dataset("mpg")

In [3]:
mpg.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320

In [10]:
#Find cars with horsepower greater than 150.
cars_hp = mpg[mpg['horsepower']>150][['name','horsepower']].head(10)
cars_hp

                       name  horsepower
1         buick skylark 320       165.0
5          ford galaxie 500       198.0
6          chevrolet impala       220.0
7         plymouth fury iii       215.0
8          pontiac catalina       225.0
9        amc ambassador dpl       190.0
10      dodge challenger se       170.0
11       plymouth 'cuda 340       160.0
13  buick estate wagon (sw)       225.0
25                ford f250       215.0

In [7]:
# Find the average MPG for each cylinder category.
avg_mpg_c = mpg.groupby('cylinders')['mpg'].mean()
avg_mpg_c

cylinders
3    20.550000
4    29.286765
5    27.366667
6    19.985714
8    14.963107
Name: mpg, dtype: float64

In [9]:
# Replace missing horsepower values with the median horsepower.
miss_hp = mpg['horsepower'].median()
#miss_hp
mpg['horsepower'].fillna(miss_hp, inplace = True)

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64

In [12]:
# Find cars with MPG between 20 and 30.
cars_mpg = mpg[(mpg['mpg']>=20) & (mpg['mpg']<=30)].reset_index()
cars_mpg

,index,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
1,15,22.0,6,198.0,95.0,2833,15.5,70,usa,plymouth duster
2,17,21.0,6,200.0,85.0,2587,16.0,70,usa,ford maverick
3,18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
4,19,26.0,4,97.0,46.0,1835,20.5,70,europe,volkswagen 1131 deluxe sedan
...,...,...,...,...,...,...,...,...,...,...
157,388,26.0,4,156.0,92.0,2585,14.5,82,usa,chrysler lebaron medallion
158,389,22.0,6,232.0,112.0,2835,14.7,82,usa,ford granada l
159,392,27.0,4,151.0,90.0,2950,17.3,82,usa,chevrolet camaro
160,393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
161,396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger

df[df["cylinders"].isin([4, 6])]

teknovis pvtlimited
9:34 AM
what will above code produce?

In [13]:
mpg.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='str')

In [16]:
# Find cars from USA with MPG greater than 25
usa_cars_25 = mpg[(mpg["origin"] == 'usa') & (mpg['mpg']>25)][['name','origin','mpg']].head(10).reset_index()
usa_cars_25

   index                     name origin   mpg
0     30      chevrolet vega 2300    usa  28.0
1     56         plymouth cricket    usa  26.0
2     83          dodge colt (sw)    usa  28.0
3    130               ford pinto    usa  26.0
4    146               dodge colt    usa  28.0
5    185               dodge colt    usa  26.0
6    195       chevrolet chevette    usa  29.0
7    206               ford pinto    usa  26.5
8    217  buick opel isuzu deluxe    usa  30.0
9    219        plymouth arrow gs    usa  25.5

In [ ]:
# Find the correlation between MPG and weight

In [17]:
#Show number of cars by cylinders.
cars_cyl = mpg['cylinders'].value_counts()
cars_cyl

cylinders
4    204
8    103
6     84
3      4
5      3
Name: count, dtype: int64

In [25]:
# Create an MPG category: <20 = Low, 20–30 = Medium, >30 = High
mpg.loc[mpg["mpg"]<20,"mpg_category"] = "Low"
mpg.loc[mpg["mpg"]>30,"mpg_category"] = "High"
mpg.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,mpg_category
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,Low
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,Low
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,Low
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,Low
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,Low
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500,Low
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala,Low
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii,Low
8,14.0,8,455.0,225.0,4425,10.0,70,usa,pontiac catalina,Low
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl,Low

In [21]:
#Find the percentage of cars in each MPG category